blank_issues_enabled: false
contact_links:
  - name: ATM Team's GitHub
    url: https://github.com/allthemods
  - name: ATM Team's Discord
    url: https://discord.gg/3paFjuRfz9
  - name: ATM Team's Reddit
    url: https://www.reddit.com/r/allthemods
  - name: ATM Team's Curseforge
    url: https://www.curseforge.com/members/atmteam